### ISSUE TITLE
style for all pages in about menu navigation

### ISSUE THREAD

**Issue by verbalhanglider** [uchicago-library/operacat-digital-collection#7]
Currently, these pages are minimally styled. Do these need extra styling or is it fine the way it is?

**Comment by verbalhanglider** [comment]
can this be closed?

**Comment by kzadrozny** [comment]
If you are OK with how they look, then yes. Otherwise we can discuss in a quick meeting any changes you would like.

**Comment by verbalhanglider** [comment]
I'm happy with it. It looks professional and the styling there lets the content be cleanly defined by different kinds of headers and paragraphs are highly readable. I'm closing this issue, in that case.
